//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTrinhWebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class AddressUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AddressUser()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int IdAddress { get; set; }
        public Nullable<int> IdUser { get; set; }
        [DisplayName("H? tên")]
        public string FullName { get; set; }
        [DisplayName("S? ði?n tho?i")]
        public string Phone { get; set; }
        [DisplayName("T?nh")]
        public string Province { get; set; }
        [DisplayName("Qu?n, huy?n, th? tr?n")]
        public string Town { get; set; }
        [DisplayName("Phý?ng, x?, ?p")]
        public string Block { get; set; }
        [DisplayName("S? nhà")]
        public string SpecificAddress { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
